# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa39eb27a9b012a5c59b4f2999177f34eb2573acd2176f88d8044fabd2693aad3775e02134dd8df5acffa475e9f49bece2bfa4c93ff898deeadd0ab4ca11d104

test:
  secret_key_base: 985c75399c1a8937dcd5526daeeca9783fe40f58d1b0eb8d5ba75fae77e78d2f56283331f257f57aa73402ad3079534814c3faf45282646c46ba8eea26a4738c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
